### ISSUE TITLE
File dependencies are lost when CNV v1.3 is called.

### ISSUE THREAD

**Issue by Puriney** [navinlabcode/CNV_pipeline#22]
```
227542 reads; of these:
  227542 (100.00%) were unpaired; of these:
    8568 (3.77%) aligned 0 times
    163703 (71.94%) aligned exactly 1 time
    55271 (24.29%) aligned >1 times
96.23% overall alignment rate
Can't exec "/volumes/seq/code/PIPELINES/CNA_pipeline_v1.3/bin/varbin.sam.2.py": No such file or directory at /volumes/seq/code/PIPELINES/Old_version_CNA/CNA_pipeline_v1.3/bin/run_bowtie2_varbin.pl line 121, <CON> line 39
```

I know the CNA_pipeline_v1.3 was moved to /volumes/seq/code/PIPELINES/Old_version_CNA/CNA_pipeline_v1.3 but there seemed some hard-coded path to /volumes/seq/code/PIPELINES/CNA_pipeline_v1.3/bin/varbin.sam.2.py.

I guess this is why the error shows up.

**Comment by darlanminussi** [comment]
I'm not sure about this error, should be same as #21 I believe, I'll close for now.

**Comment by MinBio** [comment]
old version is deprecated. you can use the latest version
