### ISSUE TITLE
long type  -- py2 and py3 compatibility

### ISSUE THREAD

**Issue by Puriney** [navinlabcode/CNV_pipeline#23]
**Problem**
The `long` numeric type is claimed in Py2 but this longer exists in Py3. When I run pipeline with Python3, error shows up as expected.

https://github.com/navinlabcode/CNV_pipeline/blob/9144bc2c15bf819955a9a73d3e6e8954598f36d2/bin/varbin.sam.2.py#L54

**Possible solution**

Simply remove `long`. This is because we require Python >=2.7.

Quoted from https://en.m.wikibooks.org/wiki/Python_Programming/Numbers: 
> Long: Integer type with unlimited length. In **python 2.2** and later, Ints are automatically turned into long ints when they overflow. Dropped since Python 3.0, use int type instead.

**Comment by MinBio** [comment]
Thank your for reporting. just noticed your message. but have used "int" instead
